language: java
script: ant
before_script:
- "./get_dependencies.sh"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QdgoSeUW/kN0YVcuaDfXkW8romzT2UNzpbpfFWRMEymtm8Fx2A3TANwfbJTe89XLM/lK4MnAZLSeF9FHBJDRMNr3cmL4mcJx/R1P4X3UZ4z/u2qEwFgRRnv+ltEy1cljH8z5fUIVcv3loYNnMTtP03zuVRl8VwoAu1OXv1DZmCy3RnVOfYHWW/nozqlmrPHQV8OC/2X4LJk8n/9J+HrZrT2OxXz28h8A++F2A/cBlSGYfb6MyRUHqFflnTvN+lfQEMFkdCyaxuZp2ZGspEbD7/47SZINoiEB9WOU+/Sp135rz0nd/uAT/k2nw1jkb1IzZ96GOxj/q9SH6RfnbYwguMe85xU/ycw1fyZS5FCUwtEL2QU8P8pbiyRPLGXoOojBPtK+ydaNu1KV/vE6HkO3H77JpWTvEh4VSPddGwjnS3UIMyumFec7IhZ2H0cdvVaX2m7EdNisB+CDSidZiSGIai03ut0SrjoYlrEnS5rcw0Q1g/dgh/ZzMqPpVWJSUbWC31nhgNYCx0DLHNZ9zgETvQvD5zNU+EHJPJcKLfMCqnDIdX+xB9jCk5clLNPDPga2kTo40XsvGw/3M4XYvWXQtjWSSYxjZlxuqjIN09MskpHhATjQuz19hyxNwO+FS5XV1uPZCuTApu1pE1A15HYrhMImR7MhjlijIPcs8rlfH5w=
  file: datacrow.jar
  on:
    repo: datacrow/client
    tags: true
